name: torch
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - anyio=3.5.0=py310h06a4308_0
  - arrow=1.2.3=py310h06a4308_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backoff=2.2.1=py310h06a4308_1
  - beautifulsoup4=4.12.2=py310h06a4308_0
  - blas=1.0=mkl
  - blessed=1.20.0=py310h06a4308_0
  - boto3=1.29.1=py310h06a4308_0
  - botocore=1.32.1=py310h06a4308_0
  - bottleneck=1.3.5=py310ha9d4c09_0
  - bowtie2=2.5.1=py310h8d7afc0_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py310h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - cd-hit=4.8.1=h43eeafb_9
  - certifi=2024.2.2=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py310h06a4308_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - comm=0.1.2=py310h06a4308_0
  - contourpy=1.0.5=py310hdb19cb5_0
  - croniter=1.3.7=py310h06a4308_0
  - cryptography=41.0.3=py310hdda0065_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.101=0
  - cuda-runtime=12.1.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dateutils=0.6.12=py310h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - deepdiff=6.7.1=py310h2f386ee_0
  - docopt=0.6.2=py310h06a4308_1
  - et_xmlfile=1.1.0=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h6a678d5_0
  - fastqc=0.12.1=hdfd78af_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py310h06a4308_0
  - flash=1.2.11=h5bf99c6_6
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - idna=3.4=py310h06a4308_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - inquirer=3.1.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.25.0=py310h2f386ee_0
  - ipython=8.15.0=py310h06a4308_0
  - ipywidgets=8.0.3=pyhd8ed1ab_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.1.2=py310h06a4308_0
  - jmespath=1.0.1=py310h06a4308_0
  - joblib=1.2.0=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jsonschema=4.21.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jupyter_client=8.6.0=py310h06a4308_0
  - jupyter_core=5.5.0=py310h06a4308_0
  - jupyterlab_widgets=3.0.9=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.8.1.2=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.4.101=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20221030=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_3
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=hdbd6064_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hf1b16e4_1
  - libzlib=1.2.13=hd590300_5
  - lightning-cloud=0.5.57=py310h06a4308_0
  - lightning-utilities=0.9.0=py310h06a4308_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown-it-py=2.2.0=py310h06a4308_1
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib=3.8.0=py310h06a4308_0
  - matplotlib-base=3.8.0=py310h1128e8f_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mdurl=0.1.0=py310h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=h721c034_2
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py310h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py310h06a4308_0
  - numba=0.58.1=py310h7dc5dd1_0
  - numexpr=2.8.7=py310h85018f9_0
  - numpy=1.26.0=py310h5f9d8c6_0
  - numpy-base=1.26.0=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjdk=11.0.13=h87a67e3_0
  - openjpeg=2.4.0=h3ad879b_0
  - openpyxl=3.0.10=py310h5eee18b_0
  - openssl=3.0.13=h7f8727e_0
  - ordered-set=4.1.0=py310h06a4308_0
  - orjson=3.9.10=py310h52d8a92_0
  - packaging=23.1=py310h06a4308_0
  - pandas=2.1.1=py310h1128e8f_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patsy=0.5.3=py310h06a4308_0
  - pcre=8.45=h295c915_0
  - perl=5.32.1=4_hd590300_perl5
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.0.1=py310ha6cbd5a_0
  - pip=23.3=py310h06a4308_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - ply=3.11=py310h06a4308_0
  - prompt-toolkit=3.0.36=py310h06a4308_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.12=py310h5eee18b_1
  - pygments=2.15.1=py310h06a4308_1
  - pyjwt=2.4.0=py310h06a4308_0
  - pyopenssl=23.2.0=py310h06a4308_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pyqt=5.15.10=py310h6a678d5_0
  - pyqt5-sip=12.13.0=py310h5eee18b_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.12=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-editor=1.0.4=pyhd3eb1b0_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-multipart=0.0.6=py310h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.1.1=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-lightning=2.0.3=py310h06a4308_0
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py310h06a4308_0
  - pyyaml=6.0.1=py310h5eee18b_0
  - pyzmq=25.1.0=py310h6a678d5_0
  - qt-main=5.15.2=h53bd1ea_10
  - readchar=4.0.5=py310h06a4308_0
  - readline=8.2=h5eee18b_0
  - referencing=0.32.1=pyhd8ed1ab_0
  - requests=2.31.0=py310h06a4308_0
  - rich=13.3.5=py310h06a4308_0
  - rpds-py=0.17.1=py310hcb5633a_0
  - s3transfer=0.7.0=py310h06a4308_0
  - scikit-learn=1.3.0=py310h1128e8f_0
  - scipy=1.11.3=py310h5f9d8c6_0
  - seaborn=0.12.2=py310h06a4308_0
  - seqkit=2.6.1=h9ee0642_0
  - seqtk=1.4=he4a0461_1
  - setuptools=68.0.0=py310h06a4308_0
  - shap=0.44.0=cpu_py310h7af0403_7
  - sip=6.7.12=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - slicer=0.0.7=pyhd8ed1ab_0
  - sniffio=1.3.0=py310h06a4308_0
  - soupsieve=2.5=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - starsessions=1.3.0=py310h06a4308_0
  - statsmodels=0.14.0=py310ha9d4c09_0
  - sympy=1.11.1=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py310h06a4308_0
  - torchaudio=2.1.1=py310_cu121
  - torchinfo=1.8.0=pyhd8ed1ab_0
  - torchmetrics=1.1.2=py310h06a4308_0
  - torchtriton=2.1.0=py310
  - torchvision=0.16.1=py310_cu121
  - tornado=6.3.3=py310h5eee18b_0
  - tqdm=4.65.0=py310h2f386ee_0
  - traitlets=5.7.1=py310h06a4308_0
  - typing-extensions=4.7.1=py310h06a4308_0
  - typing_extensions=4.7.1=py310h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.18=py310h06a4308_0
  - uvicorn=0.20.0=py310h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - websocket-client=0.58.0=py310h06a4308_4
  - websockets=10.4=py310h5eee18b_1
  - wheel=0.41.2=py310h06a4308_0
  - widgetsnbextension=4.0.9=pyhd8ed1ab_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_0
  - pip:
      - accelerate==0.28.0
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - argcomplete==3.2.2
      - argh==0.31.2
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arviz==0.17.0
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==21.4.0
      - babel==2.14.0
      - beartype==0.17.2
      - binaryornot==0.4.4
      - biopython==1.81
      - bioservices==1.11.2
      - bleach==6.1.0
      - boto==2.49.0
      - cachetools==5.3.3
      - cattrs==23.2.3
      - chardet==5.2.0
      - cloudml-hypertune==0.1.0.dev6
      - cmake==3.28.3
      - colorama==0.4.6
      - colorlog==6.8.2
      - cookiecutter==2.6.0
      - crcmod==1.7
      - cython==3.0.9
      - deeplift==0.6.13.0
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - discrete-key-value-bottleneck-pytorch==0.1.1
      - dmslogo==0.6.2
      - easydev==0.13.1
      - einops==0.7.0
      - einx==0.1.3
      - enformer-pytorch==0.8.8
      - exceptiongroup==1.2.0
      - fastapi==0.88.0
      - fasteners==0.19
      - fonttools==4.50.0
      - fqdn==1.5.1
      - frozendict==2.4.0
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - future==1.0.0
      - gcs-oauth2-boto-plugin==3.0
      - gcsfs==2023.12.2.post1
      - gevent==24.2.1
      - gffutils==0.12
      - google-api-core==2.17.1
      - google-apitools==0.5.32
      - google-auth==2.28.1
      - google-auth-oauthlib==1.2.0
      - google-cloud-aiplatform==1.43.0
      - google-cloud-bigquery==3.18.0
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.12.2
      - google-cloud-storage==2.15.0
      - google-crc32c==1.5.0
      - google-reauth==0.1.1
      - google-resumable-media==2.7.0
      - googleapis-common-protos==1.62.0
      - gpytorch==1.11
      - greenlet==3.0.3
      - grequests==0.7.0
      - grpc-google-iam-v1==0.13.0
      - grpcio==1.62.0
      - grpcio-status==1.62.0
      - gsutil==5.27
      - h11==0.14.0
      - h5netcdf==1.3.0
      - h5py==3.10.0
      - hdf5plugin==4.3.0
      - httpcore==1.0.4
      - httplib2==0.20.4
      - httpx==0.27.0
      - huggingface-hub==0.21.4
      - hypertune==1.1.0
      - igraph==0.9.11
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.4
      - importlib-metadata==6.8.0
      - isoduration==20.11.0
      - jaxtyping==0.2.25
      - json5==0.9.20
      - jsonpointer==2.4
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.3
      - jupyter-server==2.13.0
      - jupyter-server-terminals==0.5.2
      - jupyterlab==4.1.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.3
      - keopscore==2.2.2
      - kipoi==0.8.6
      - kipoi-conda==0.3.1
      - kipoi-utils==0.7.7
      - kipoiseq==0.7.1
      - leidenalg==0.8.10
      - levenshtein==0.23.0
      - lightning==1.9.5
      - line-profiler==4.1.2
      - linear-operator==0.5.2
      - llvmlite==0.41.1
      - logomaker==0.8
      - lxml==5.1.0
      - mistune==3.0.2
      - modisco-lite==2.2.0
      - monotonic==1.6
      - multidict==6.0.5
      - natsort==8.4.0
      - nbclient==0.9.0
      - nbconvert==7.16.2
      - ncls==0.0.68
      - nose==1.3.7
      - notebook==7.1.1
      - notebook-shim==0.2.4
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - overrides==7.7.0
      - palettable==3.3.0
      - pandocfilters==1.5.1
      - pexpect==4.9.0
      - platformdirs==4.2.0
      - plotly==5.19.0
      - polars==0.20.16
      - prometheus-client==0.20.0
      - proto-plus==1.23.0
      - protobuf==4.25.3
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pybedtools==0.9.1
      - pybind11==2.11.1
      - pyfaidx==0.8.1.1
      - pykeops==2.2.2
      - pyranges==0.0.129
      - pyro-api==0.1.2
      - pyro-ppl==1.9.0
      - pysam==0.22.0
      - pytabix==0.1
      - python-json-logger==2.0.7
      - python-levenshtein==0.23.0
      - python-slugify==8.0.4
      - pyu2f==0.1.5
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - rapidfuzz==3.5.2
      - regex==2023.12.25
      - related==0.7.3
      - requests-cache==1.2.0
      - requests-oauthlib==1.3.1
      - retry-decorator==1.1.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rotary-embedding-torch==0.5.3
      - rsa==4.7.2
      - safetensors==0.4.2
      - selene-sdk==0.5.0
      - send2trash==1.8.2
      - shapely==2.0.3
      - simplejson==3.19.2
      - sorted-nearest==0.0.39
      - starlette==0.22.0
      - suds-community==1.1.2
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorly==0.8.1
      - tensorly-torch==0.4.0
      - terminado==0.18.0
      - text-unidecode==1.3
      - texttable==1.7.0
      - tinycss2==1.2.1
      - tinydb==4.8.0
      - tokenizers==0.15.2
      - torchsummary==1.5.1
      - transformers==4.38.2
      - typeguard==2.13.3
      - uri-template==1.3.0
      - url-normalize==1.4.3
      - vector-quantize-pytorch==1.14.1
      - webcolors==1.13
      - webencodings==0.5.1
      - wordcloud==1.9.3
      - wrapt==1.16.0
      - xarray==2024.2.0
      - xarray-einstats==0.7.0
      - xlrd==2.0.1
      - xmltodict==0.13.0
      - yarl==1.9.4
      - zope-event==5.0
      - zope-interface==6.2
prefix: /home/hxcai/anaconda3/envs/torch
